export default {
    registerTeam: "http://localhost:5000/team",
    logIn: "http://localhost:5000/authenticate/login",
    register: "http://localhost:5000/authenticate/register",
    getTeams: "http://localhost:5000/team/get",
    getTeam: "http://localhost:5000/team",
    joinTeam: "http://localhost:5000/invite",
    createInvite: "http://localhost:5000/invite",
    teamTasks: "http://localhost:5000/tasks",
    createTask: "http://localhost:5000/tasks",
    notificationCount: "http://localhost:5000/notifications/count",
    notifications: "http://localhost:5000/notifications",
    deleteTask: "http://localhost:5000/tasks",
    updateNotifications: "http://localhost:5000/notifications",
    getMyTasks: "http://localhost:5000/tasks/mytasks",
    setTask: "http://localhost:5000/tasks",
    leaveTeam: "http://localhost:5000/team/leave",
    deleteTeam: "http://localhost:5000/team",
    getUser: "http://localhost:5000/users",
    followUser: "http://localhost:5000/follow",
    publishPost: "http://localhost:5000/post",
    getOrientations: "http://localhost:5000/orientations",
    getTeamTypes: "http://localhost:5000/teamtypes",
}